### ISSUE TITLE
Checkbox

### ISSUE THREAD

**Issue by mitkosaxa** [melnik909/material_bootstrap_theme#6]
Hi, thanks for the awesome theme ! 
I want to use syntax like this 

`<div class="material-checkbox-group">
 <label class="material-checkbox-group__label" >
<input type="checkbox"  name="checkbox" class="material-checkbox">
 Do you like it?
</label>
</div>`

can you tell me how to fix checkbox.scss to work. I want to skip use ID's.
Thanks in advance !

**Comment by melnik909** [comment]
Use empty tags span with .before and .after classes instead of the :after and :before. 

`<div class="material-checkbox-group"> <label class="material-checkbox-group__label" > 
<span class="before"></span>
<input type="checkbox" name="checkbox" class="material-checkbox"> Do you like it?  
<span class="after"></span>
</label>
</div>`

And replace ".material-checkbox:checked + .material-checkbox-group__label:after" on ".material-checkbox:checked + .after".

```
.before{
    display: block;
    border: 2px solid #eee;
    width: 25px;
    height: 25px;
    position: absolute;
    left: 0;
}

.after{
    width: 5px;
    height: 15px;
    opacity: .9;
    border-right: 2px solid #eee;
    border-top: 2px solid #eee;
    position: absolute;
    left: 5px;
    top: 15px;
    transform: scaleX(-1) rotate(135deg);
    transform-origin: left top;
}

.material-checkbox-group .material-checkbox:checked + .after{
    animation: check 0.8s;
    opacity: 1;
    border-color: #000;
}
```

**Comment by mitkosaxa** [comment]
I try to use these and work well. Don't need any changes in CSS classes. Thank you !
`<div class="material-checkbox-group"> 
<label> 
<input type="checkbox" name="checkbox" class="material-checkbox"> 
<span class="material-checkbox-group__label" >Do you like it? </span>
</label> 
</div>`
